# Generated by Django 5.1.3 on 2024-12-13 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
