# Generated by Django 5.1.3 on 2024-12-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_event_options_remove_event_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="participants",
        ),
        migrations.AddField(
            model_name="event",
            name="max_participants",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
