# Generated by Django 5.1.3 on 2024-12-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_event_options_event_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="description",
            field=models.CharField(
                blank=True, default="เพิ่มคำอธิบายของคุณ", max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
